language: go
go:
- 1.9.x
before_install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u golang.org/x/tools/cmd/cover
- go get -u github.com/mattn/goveralls
install:
- dep ensure
script:
- cd common && go test -v -covermode=count -coverprofile=../coverage.out
- cd common && $HOME/gopath/bin/goveralls -coverprofile=../coverage.out -service=travis-ci
