language: go
go:
- 1.9.x
before_install:
- go get -u github.com/golang/dep/cmd/dep
- go get -u golang.org/x/tools/cmd/cover
- go get -u github.com/mattn/goveralls
install:
- dep ensure
script:
- go test -v -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN"
dd:
  secure: FrZ9y+ZG7AuyUwQvmqUs+B1Lxncr5xiXqXLM7YdM4dl1jFe6OYgMTflbY5W70yk53op2z1e6AruN+to62EoSUfT/qRINb7qTZLbBIum/rr7WN+DIcNxL5cxDn6rbgXMy5vOV2j7TQ6b46g0m/VHP2D1MOtHztYVtogfiPCIVILs17YP++xaoavYCokrRVWhsgqYxQX8os47Ze1HF7JOV95FBVGYHAITMdGvI6q5Cg5rWywBum6hWjL0TuZP8AAp3f92cqJM3G9PLOAJ6MVk/EiuNZOBELZPILXsd7HPm18CjWva5jx+bT6k1XAkhr5V1KZHMev+wUH+roLcOQT6nP5VLKhp1cy5W/diIGXP6opoC9YfWsr/QB+V8kq5mB/Zw47CF+n7TnbeZHw58ZmKxWjq3ugGQRpYmcaOFG4AIqVZhOdCsFeMkHjgCnhS6af3FSjOpRsRv8z++h/3v8LGYLUKxQq0osqCfZUN1L5f/iRE8YAE6CPRBM6hXUGmdKswpSwWqd/eFgg7JZN0dT2cVFV6fRPPtiyv1AwFGBKE8xWpy9TN7aEBRNfgCKDs8jDjdUOMyEP0bnIcI4P+madv06+9XflFdqwrrUKNqfGvrgGV8o8mnlN6eBGEdqCXR5Q9EvG6DZ8NdK3/9YvOZ0QVFZvDbzTY2nQigfZfyH//+u4Q=
