# Gopkg.toml
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[projects]]
  name = "github.com/ethereum/go-ethereum"
  packages = [
    ".",
    "accounts",
    "accounts/abi",
    "accounts/abi/bind",
    "accounts/keystore",
    "common",
    "common/hexutil",
    "common/math",
    "common/mclock",
    "core/types",
    "crypto",
    "crypto/randentropy",
    "crypto/secp256k1",
    "crypto/sha3",
    "ethclient",
    "ethdb",
    "event",
    "log",
    "metrics",
    "params",
    "rlp",
    "rpc",
    "trie"
  ]
  version = "v1.7.3"
